# Generated by Django 5.1.5 on 2025-01-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useractivity_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='login_time',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='total_session_time',
            field=models.IntegerField(default=0),
        ),
    ]
