# Generated by Django 5.1.5 on 2025-01-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_useractivity_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
