# Generated by Django 5.1.5 on 2025-01-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_total_session_time_useractivity_session_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='session_time',
            new_name='total_session_time',
        ),
    ]
