# Generated by Django 5.1.5 on 2025-01-29 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_session_time_useractivity_total_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='last_session_time',
            field=models.IntegerField(default=0),
        ),
    ]
