# Generated by Django 5.1.5 on 2025-01-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_useractivity_last_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
